Trc 16 storybook
wijohnst/ts_reddit_clone pull request #17
Opened 2023-02-17 16:06 UTC by mmcbride2929

2023-02-18 02:44 UTC, mmcbride2929 commented
Happy to get storybook running. If I had to redo this again, I would have made more precise commits.

2023-02-18 21:32 UTC, wijohnst requested changes
Good start. The majority of the files that were added are Storybook boilerplate. Let's remove all of those before merging with `main`.

2023-02-18 21:32 UTC, wijohnst commented on apps/web/package.json
> +    "concurrently": "^7.6.0",
What are these dependencies?

2023-02-18 21:32 UTC, wijohnst commented on apps/web/src/components/Button.tsx
> +const Button = () => {
Should have `react` in scope and should be typed.

2023-02-18 21:32 UTC, wijohnst commented on apps/web/src/stories/Button.tsx
> + */
Take note of the syntax for all of these comments. It uses this special character set to prefix each multiline comment:

```
/**
```

This is called JSDocs and it is a special kind of comment that can be referenced from the calling scope of the code and use to automate documentation. In our codebase all component props should be commented with JSDocs, just like this example. 

Additionally, all functions should be documented like this:

```ts
/**
* A simple function that adds its two parameters together
*
* @param { number } num1 - the first number to add
* @param { number } num2 - the second numebr to add
* @returns { number }
*/
const sum = (num1: number, num2: number) : number => num1 + num2;
```
Functions should document all of their params, including name and type as well as their return type. Additionally they should have a brief description of what the function does.

You can add the [JSDoc Extension](https://marketplace.visualstudio.com/items?itemName=lllllllqw.jsdoc) to VSCode and easily generate JSDocs templates:

![js_docs](https://user-images.githubusercontent.com/12022922/219900362-81289f4d-95e1-4935-a28f-801d68b51569.gif)

2023-02-18 21:32 UTC, wijohnst commented on package.json
> +    "storybook": "turbo run storybook "
Looks good.

2023-02-19 16:49 UTC, wijohnst approved these changes
Thank you for taking the time to make those changes. Everything looks great. Happy to approve.

2023-02-19 18:38 UTC, merged